# Generated by Django 2.1.1 on 2018-09-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kickstarter_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='kickstarter_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
